<a href="https://colab.research.google.com/github/lich333/rct-classfication/blob/main/diagnosis_of_rct.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
data = pd.read_csv("/content/drive/MyDrive/rct_machinelearning/lcc.csv",header=None)
data.head()

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
0,10009,Female,70.0,0,6.0,7,0.0,90.0,90.0,0.0,...,3.0,4.0,3.0,55.0,32.0,46.0,20.0,1.0,1,NaN
1,10010,Female,59.0,0,NaN,0,1.0,170.0,60.0,60.0,...,4.0,4.0,4.0,75.0,2.0,75.0,31.0,9.0,1,NaN
2,10031,Female,53.0,0,NaN,6,1.0,100.0,90.0,60.0,...,5.0,5.0,4.0,NaN,NaN,NaN,NaN,NaN,1,NaN
3,10045,Female,61.0,0,NaN,1,1.0,180.0,180.0,60.0,...,5.0,5.0,5.0,82.0,11.0,78.0,24.0,7.0,1,NaN
4,10050,Female,50.0,0,10.0,4,NaN,90.0,90.0,60.0,...,4.0,5.0,4.0,NaN,NaN,NaN,NaN,NaN,1,NaN

In [8]:
data = data.sample(frac=1)

In [9]:
columns = ['ID','Sex' , 'Age' ,'Dominant side operated' ,'vas' , 'Time','Trauma-related','Flex' , 'Abd' , 'ER' , 'IR' , 'Jobe' , 'Bear hug' ,'Belly press' ,'ERLS' ,  'SS','IS','SSC','ASES' , 'Quick-DASH' ,'Constant-Murley','UCLA','SST' , 'classier','we']

In [10]:
list1 = np.arange(25)
list1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [12]:
dict1 = dict(zip(list1,columns))
data = data.rename(columns=dict1)

In [14]:
data['IR'] = data['IR'].replace(to_replace=['thi','butt','S 1','L5','L 3','L 1','T 11','T 9','T 7','T 5','T 3'],value=[0,1,2,3,4,5,6,7,8,9,10])
data['Sex'] = data['Sex'].replace(to_replace=['Male','Female',],value=[0,1])

In [15]:
data['Trauma-related'] = data['Trauma-related'].fillna(value= 0)

In [16]:
data = data.drop(['we'], axis=1)

In [17]:
data1 = data
data1.set_index('ID',inplace=True)
data1

,Sex,Age,Dominant side operated,vas,Time,Trauma-related,Flex,Abd,ER,IR,...,ERLS,SS,IS,SSC,ASES,Quick-DASH,Constant-Murley,UCLA,SST,classier
ID,,,,,,,,,,,,,,,,,,,,,
11170,0,39.0,0,NaN,1,1.0,180.0,180.0,70.0,10.0,...,0.0,4.0,5.0,5.0,NaN,NaN,NaN,NaN,NaN,0
11068,0,61.0,0,NaN,0,0.0,180.0,180.0,70.0,9.0,...,0.0,3.0,3.0,5.0,NaN,NaN,NaN,NaN,NaN,0
12358,1,52.0,1,6.0,6,0.0,180.0,180.0,60.0,8.0,...,0.0,4.0,5.0,5.0,62.0,18.0,67.0,19.0,9.0,0
11736,1,58.0,1,7.0,12,0.0,180.0,180.0,80.0,10.0,...,0.0,4.0,5.0,5.0,77.0,20.0,88.0,25.0,10.0,0
12016,1,57.0,1,7.0,2,0.0,180.0,170.0,80.0,9.0,...,1.0,3.0,5.0,4.0,63.0,11.0,65.0,21.0,9.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11708,0,15.0,0,0.0,9,0.0,180.0,180.0,80.0,10.0,...,0.0,5.0,5.0,5.0,100.0,0.0,100.0,35.0,12.0,0
10235,0,50.0,0,1.0,2,0.0,130.0,130.0,40.0,1.0,...,0.0,4.0,5.0,5.0,57.0,18.0,65.0,16.0,6.0,0
12214,0,78.0,0,2.0,37,0.0,130.0,120.0,50.0,3.0,...,0.0,5.0,3.0,5.0,70.0,23.0,83.0,22.0,6.0,0
10363,0,50.0,0,4.0,4,1.0,180.0,180.0,70.0,9.0,...,0.0,5.0,5.0,5.0,NaN,NaN,NaN,NaN,NaN,0
12143,1,54.0,0,6.0,3,0.0,100.0,70.0,20.0,1.0,...,0.0,4.0,4.0,4.0,42.0,61.0,45.0,13.0,3.0,0

In [19]:
data_ = data1.copy()
data_B = data_[data_['classier'] == 1]
data_C = data_[data_['classier'] == 0]

In [21]:
data_B = data_B.fillna(value = data_B.mean())
# data_B.info()
data_C = data_C.fillna(value = data_C.mean())
# data_C.info()
data_ = pd.concat((data_C,data_B))
data_.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1945 entries, 11170 to 11152
Data columns (total 23 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Sex                     1945 non-null   int64
 1   Age                     1945 non-null   float64
 2   Dominant side operated  1945 non-null   int64
 3   vas                     1945 non-null   float64
 4   Time                    1945 non-null   int64
 5   Trauma-related          1945 non-null   float64
 6   Flex                    1945 non-null   float64
 7   Abd                     1945 non-null   float64
 8   ER                      1945 non-null   float64
 9   IR                      1945 non-null   float64
 10  Jobe                    1945 non-null   float64
 11  Bear hug                1945 non-null   float64
 12  Belly press             1945 non-null   float64
 13  ERLS                    1945 non-null   float64
 14  SS                      1945 non-null   float64
 15  IS                      1945 non-null   float64
 16  SSC                     1945 non-null   float64
 17  ASES                    1945 non-null   float64
 18  Quick-DASH              1945 non-null   float64
 19  Constant-Murley         1945 non-null   float64
 20  UCLA                    1945 non-null   float64
 21  SST                     1945 non-null   float64
 22  classier                1945 non-null   int64
dtypes: float64(19), int64(4)
memory usage: 364.7 KB

In [22]:
cc = [-1,45,90,135,190]
aa = [-1,45,90,135,190]
bb = [-1,20,40,60,90]
dd = [-1,5,8,11]
ee = [-10,3,7,11]
ff = [-10,3,6,12,1000]

flexlabels = ['a','b','c','d']
abdlabels = ['e','f','g','h']
erlabels = ['i','j','k','l']
irlables = ['q','w','e']
vaslables = ['q','w','e']
timelables = ['q','w','e','r']

pd.cut(data_['Flex'],cc,labels=flexlabels)
pd.cut(data_['Abd'],aa,labels=abdlabels)
pd.cut(data_['ER'],bb,labels=erlabels)
pd.cut(data_['IR'],dd,labels=irlables)
pd.cut(data_['vas'],ee,labels=vaslables)
pd.cut(data_['Time'],ff,labels=timelables)

data_['Flexion'] = pd.cut(data_['Flex'],cc,labels=flexlabels)
data_['Abduction'] = pd.cut(data_['Abd'],aa,labels=abdlabels)
data_['External rotation'] = pd.cut(data_['ER'],bb,labels=erlabels)
data_['Internal rotation'] = pd.cut(data_['IR'],dd,labels=irlables)
data_['VAS'] = pd.cut(data_['vas'],ee,labels=vaslables)
data_['Duration of symptoms'] = pd.cut(data_['Time'],ff,labels=timelables)

data_['Flexion'] = data_['Flexion'].replace(to_replace=['a','b','c','d'],value=[0,1,2,3])
data_['Abduction'] = data_['Abduction'].replace(to_replace=['e','f','g','h'],value=[0,1,2,3])
data_['External rotation'] = data_['External rotation'].replace(to_replace=['i','j','k','l'],value=[0,1,2,3])
data_['Internal rotation'] = data_['Internal rotation'].replace(to_replace=['q','w','e'],value=[0,1,2])
data_['VAS'] = data_['VAS'].replace(to_replace=['q','w','e'],value=[0,1,2])
data_['Duration of symptoms'] = data_['Duration of symptoms'].replace(to_replace=['q','w','e','r'],value=[0,1,2,3])

data_.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1945 entries, 11170 to 11152
Data columns (total 29 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Sex                     1945 non-null   int64
 1   Age                     1945 non-null   float64
 2   Dominant side operated  1945 non-null   int64
 3   vas                     1945 non-null   float64
 4   Time                    1945 non-null   int64
 5   Trauma-related          1945 non-null   float64
 6   Flex                    1945 non-null   float64
 7   Abd                     1945 non-null   float64
 8   ER                      1945 non-null   float64
 9   IR                      1945 non-null   float64
 10  Jobe                    1945 non-null   float64
 11  Bear hug                1945 non-null   float64
 12  Belly press             1945 non-null   float64
 13  ERLS                    1945 non-null   float64
 14  SS                      1945 non-null   float64
 15  IS                      1945 non-null   float64
 16  SSC                     1945 non-null   float64
 17  ASES                    1945 non-null   float64
 18  Quick-DASH              1945 non-null   float64
 19  Constant-Murley         1945 non-null   float64
 20  UCLA                    1945 non-null   float64
 21  SST                     1945 non-null   float64
 22  classier                1945 non-null   int64
 23  Flexion                 1945 non-null   int64
 24  Abduction               1945 non-null   int64
 25  External rotation       1945 non-null   int64
 26  Internal rotation       1945 non-null   int64
 27  VAS                     1945 non-null   int64
 28  Duration of symptoms    1945 non-null   int64
dtypes: float64(19), int64(10)
memory usage: 455.9 KB

In [23]:
features = data_.drop(columns=['classier','vas','Time','Flex' , 'Abd' , 'ER' , 'IR' ,'SST','Quick-DASH'])
features

,Sex,Age,Dominant side operated,Trauma-related,Jobe,Bear hug,Belly press,ERLS,SS,IS,SSC,ASES,Constant-Murley,UCLA,Flexion,Abduction,External rotation,Internal rotation,VAS,Duration of symptoms
ID,,,,,,,,,,,,,,,,,,,,
11170,0,39.0,0,1.0,1.0,1.0,0.0,0.0,4.0,5.0,5.0,62.650342,72.527569,22.991105,3,3,3,2,1,0
11068,0,61.0,0,0.0,1.0,0.0,0.0,0.0,3.0,3.0,5.0,62.650342,72.527569,22.991105,3,3,3,2,1,0
12358,1,52.0,1,0.0,1.0,0.0,0.0,0.0,4.0,5.0,5.0,62.000000,67.000000,19.000000,3,3,2,1,1,1
11736,1,58.0,1,0.0,1.0,0.0,0.0,0.0,4.0,5.0,5.0,77.000000,88.000000,25.000000,3,3,3,2,1,2
12016,1,57.0,1,0.0,0.0,0.0,1.0,1.0,3.0,5.0,4.0,63.000000,65.000000,21.000000,3,3,3,2,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12279,0,62.0,1,1.0,1.0,1.0,0.0,0.0,4.0,4.0,5.0,60.000000,84.000000,19.000000,3,3,2,1,1,1
11773,0,68.0,0,1.0,1.0,1.0,1.0,0.0,4.0,5.0,4.0,65.000000,46.000000,17.000000,1,1,1,0,0,0
11930,0,72.0,1,1.0,1.0,1.0,1.0,0.0,4.0,4.0,4.0,25.000000,76.000000,10.000000,3,3,1,0,1,0
12060,0,60.0,0,0.0,1.0,1.0,1.0,0.0,4.0,5.0,4.0,50.000000,79.000000,28.000000,3,3,3,0,1,1
11152,1,49.0,0,1.0,1.0,1.0,1.0,0.0,4.0,5.0,4.0,65.000000,70.000000,20.000000,3,3,3,1,0,1

In [25]:
target = data_.classier
target

ID
11170    0
11068    0
12358    0
11736    0
12016    0
        ..
12279    1
11773    1
11930    1
12060    1
11152    1
Name: classier, Length: 1945, dtype: int64

In [26]:
from sklearn.preprocessing import StandardScaler,MinMaxScaler
transfer= StandardScaler()
features_ = transfer.fit_transform(features)
from sklearn.model_selection import train_test_split
train_features, test_features, train_target, test_target = train_test_split(features,target,test_size = 0.2, random_state = 99)
print(train_features.shape)
print(train_target.shape)
print(test_features.shape)
print(test_target.shape)

(1556, 20)
(1556,)
(389, 20)
(389,)

In [28]:
from sklearn.model_selection import KFold,ShuffleSplit,cross_val_score
kf = KFold(n_splits=10)
ss = ShuffleSplit(n_splits=10, test_size=0.2, random_state=99)
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
log_clf = LogisticRegression(solver='liblinear')
svm_clf = SVC()
tree_clf = DecisionTreeClassifier()
from sklearn.ensemble import VotingClassifier
voting_clf = VotingClassifier(
    estimators=[('lr', log_clf), ('svc', svm_clf), ('tree', tree_clf)],
    voting='hard')
voting_clf.fit(train_features, train_target)

VotingClassifier(estimators=[('lr', LogisticRegression(solver='liblinear')),
                             ('svc', SVC()),
                             ('tree', DecisionTreeClassifier())])

In [29]:
from sklearn.metrics import confusion_matrix, roc_curve,accuracy_score,precision_score,recall_score

In [32]:
from sklearn.metrics import classification_report
>>> y_true = test_target
>>> y_pred = voting_clf.predict(test_features)
>>> target_names = ['RCT', 'none']
>>> print(classification_report(y_true, y_pred, target_names=target_names))

              precision    recall  f1-score   support

         RCT       0.81      0.97      0.88       302
        none       0.68      0.20      0.30        87

    accuracy                           0.80       389
   macro avg       0.74      0.58      0.59       389
weighted avg       0.78      0.80      0.75       389

In [33]:
from sklearn.ensemble import RandomForestClassifier
np.random.seed(42)
for i in range(1,40,1):
  print(f"With {i*10} estimators:")
  clf2=RandomForestClassifier(n_estimators=i*10,max_depth=i,random_state=i).fit(train_features,train_target)
  print(f"Accuracy: {clf2.score(test_features,test_target)*100:2f}%")

With 10 estimators:
Accuracy: 77.634961%
With 20 estimators:
Accuracy: 78.149100%
With 30 estimators:
Accuracy: 81.491003%
With 40 estimators:
Accuracy: 83.033419%
With 50 estimators:
Accuracy: 81.491003%
With 60 estimators:
Accuracy: 83.547558%
With 70 estimators:
Accuracy: 83.547558%
With 80 estimators:
Accuracy: 84.318766%
With 90 estimators:
Accuracy: 84.318766%
With 100 estimators:
Accuracy: 83.033419%
With 110 estimators:
Accuracy: 83.547558%
With 120 estimators:
Accuracy: 83.547558%
With 130 estimators:
Accuracy: 84.832905%
With 140 estimators:
Accuracy: 83.290488%
With 150 estimators:
Accuracy: 82.005141%
With 160 estimators:
Accuracy: 82.519280%
With 170 estimators:
Accuracy: 83.547558%
With 180 estimators:
Accuracy: 83.033419%
With 190 estimators:
Accuracy: 84.318766%
With 200 estimators:
Accuracy: 83.290488%
With 210 estimators:
Accuracy: 83.290488%
With 220 estimators:
Accuracy: 83.804627%
With 230 estimators:
Accuracy: 84.318766%
With 240 estimators:
Accuracy: 84.061697%
With 250 estimators:
Accuracy: 83.290488%
With 260 estimators:
Accuracy: 83.547558%
With 270 estimators:
Accuracy: 83.290488%
With 280 estimators:
Accuracy: 83.804627%
With 290 estimators:
Accuracy: 84.318766%
With 300 estimators:
Accuracy: 82.519280%
With 310 estimators:
Accuracy: 83.804627%
With 320 estimators:
Accuracy: 83.290488%
With 330 estimators:
Accuracy: 84.575835%
With 340 estimators:
Accuracy: 83.547558%
With 350 estimators:
Accuracy: 85.089974%
With 360 estimators:
Accuracy: 84.061697%
With 370 estimators:
Accuracy: 84.061697%
With 380 estimators:
Accuracy: 82.776350%
With 390 estimators:
Accuracy: 84.061697%

In [41]:
import xgboost
xgb_clf = xgboost.XGBClassifier(learning_rate=0.3,
    n_estimators=20,
    seed=20,
    verbosity=1
)
xgb_clf.fit(train_features, train_target)
from sklearn.metrics import brier_score_loss as BS
y_true = test_target
y_pred = xgb_clf.predict(test_features)
BS(y_true,y_pred)

0.14395886889460155

In [42]:
from sklearn.metrics import classification_report
>>> y_true = test_target
>>> y_pred = xgb_clf.predict(test_features)
>>> target_names = ['RCT', 'none']
>>> print(classification_report(y_true, y_pred, target_names=target_names))

              precision    recall  f1-score   support

         RCT       0.89      0.93      0.91       302
        none       0.71      0.60      0.65        87

    accuracy                           0.86       389
   macro avg       0.80      0.76      0.78       389
weighted avg       0.85      0.86      0.85       389

In [54]:
# !pip install shap
# import shap
# import numpy
# import sklearn

In [45]:
# # Create object that can calculate shap values
# explainer = shap.TreeExplainer(xgb_clf)
# # Calculate Shap values
# shap_values = explainer.shap_values(train_features)

In [55]:
# shap_sum = np.abs(shap_values).mean(axis=0)
# importance_df = pd.DataFrame([train_features.columns.tolist(), shap_sum.tolist()]).T
# importance_df.columns = ['column_name', 'shap_importance']
# importance_df = importance_df.sort_values('shap_importance', ascending=False)
# importance_df

In [56]:
# shap.summary_plot(shap_values,train_features,plot_type="bar",show = False)
# myfig = plt.gcf()
# myfig.savefig('./figure1.tiff',bbox_inches='tight',dpi=300)

In [57]:
# shap.summary_plot(shap_values, train_features, feature_names=train_features.columns,show = False)

# myfig = plt.gcf()
# myfig.savefig('./figure2.tiff',bbox_inches='tight',dpi=600)

In [ ]:
# from sklearn.metrics import plot_roc_curve
# import matplotlib.pylab as plt
# f1_disp = plot_roc_curve(clf, test_features, test_target)
# f2_disp = plot_roc_curve(stk_clf, test_features, test_target,ax =f1_disp.ax_)
# f3_disp = plot_roc_curve(bag_clf, test_features, test_target,ax =f2_disp.ax_)
# f4_disp = plot_roc_curve(ada_clf, test_features, test_target,ax =f3_disp.ax_)
# f5_disp = plot_roc_curve(gra_clf, test_features, test_target,ax =f4_disp.ax_)
# f6_disp = plot_roc_curve(rfc_clf, test_features, test_target,ax =f5_disp.ax_)
# f7_disp = plot_roc_curve(xgb_clf, test_features, test_target,ax =f6_disp.ax_)
# f7_disp.figure_.suptitle("ROC curve comparison")
# myfig = plt.gcf()
# myfig.savefig('./figure3.tiff',dpi=300) 
# plt.show()

In [53]:
# from sklearn.metrics import plot_confusion_matrix, plot_roc_curve

# plot_confusion_matrix(xgb_clf, test_features, test_target)

# plot_roc_curve(xgb_clf, test_features, test_target)

In [58]:
import pickle as pkl
pkl.dump(xgb_clf,open("final_model.p","wb"))

In [59]:
import sklearn
sklearn_version = sklearn.__version__
print(sklearn_version)

1.0.2

In [60]:
!pip install streamlit
!pip install pyngrok===4.1.1
from pyngrok import ngrok

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting streamlit
  Downloading streamlit-1.10.0-py2.py3-none-any.whl (9.1 MB)
     |████████████████████████████████| 9.1 MB 5.7 MB/s
Requirement already satisfied: protobuf<4,>=3.12 in /usr/local/lib/python3.7/dist-packages (from streamlit) (3.17.3)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.7/dist-packages (from streamlit) (2.8.2)
Requirement already satisfied: pandas>=0.21.0 in /usr/local/lib/python3.7/dist-packages (from streamlit) (1.3.5)
Collecting watchdog
  Downloading watchdog-2.1.9-py3-none-manylinux2014_x86_64.whl (78 kB)
     |████████████████████████████████| 78 kB 7.1 MB/s
Collecting pydeck>=0.1.dev5
  Downloading pydeck-0.7.1-py2.py3-none-any.whl (4.3 MB)
     |████████████████████████████████| 4.3 MB 36.5 MB/s
Requirement already satisfied: cachetools>=4.0 in /usr/local/lib/python3.7/dist-packages (from streamlit) (4.2.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.7/dist-packages (from streamlit) (21.3)
Requirement already satisfied: tornado>=5.0 in /usr/local/lib/python3.7/dist-packages (from streamlit) (5.1.1)
Requirement already satisfied: tzlocal in /usr/local/lib/python3.7/dist-packages (from streamlit) (1.5.1)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.7/dist-packages (from streamlit) (7.1.2)
Collecting toml
  Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
Requirement already satisfied: altair>=3.2.0 in /usr/local/lib/python3.7/dist-packages (from streamlit) (4.2.0)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from streamlit) (2.23.0)
Collecting validators
  Downloading validators-0.20.0.tar.gz (30 kB)
Requirement already satisfied: attrs in /usr/local/lib/python3.7/dist-packages (from streamlit) (21.4.0)
Collecting gitpython!=3.1.19
  Downloading GitPython-3.1.27-py3-none-any.whl (181 kB)
     |████████████████████████████████| 181 kB 51.5 MB/s
Collecting blinker
  Downloading blinker-1.4.tar.gz (111 kB)
     |████████████████████████████████| 111 kB 43.6 MB/s
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from streamlit) (1.21.6)
Requirement already satisfied: pyarrow in /usr/local/lib/python3.7/dist-packages (from streamlit) (6.0.1)
Collecting pympler>=0.9
  Downloading Pympler-1.0.1-py3-none-any.whl (164 kB)
     |████████████████████████████████| 164 kB 48.5 MB/s
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from streamlit) (4.1.1)
Requirement already satisfied: importlib-metadata>=1.4 in /usr/local/lib/python3.7/dist-packages (from streamlit) (4.11.4)
Collecting rich
  Downloading rich-12.4.4-py3-none-any.whl (232 kB)
     |████████████████████████████████| 232 kB 52.6 MB/s
Requirement already satisfied: click>=7.0 in /usr/local/lib/python3.7/dist-packages (from streamlit) (7.1.2)
Requirement already satisfied: semver in /usr/local/lib/python3.7/dist-packages (from streamlit) (2.13.0)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.7/dist-packages (from altair>=3.2.0->streamlit) (0.4)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.7/dist-packages (from altair>=3.2.0->streamlit) (2.11.3)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.7/dist-packages (from altair>=3.2.0->streamlit) (4.3.3)
Requirement already satisfied: toolz in /usr/local/lib/python3.7/dist-packages (from altair>=3.2.0->streamlit) (0.11.2)
Collecting gitdb<5,>=4.0.1
  Downloading gitdb-4.0.9-py3-none-any.whl (63 kB)
     |████████████████████████████████| 63 kB 1.6 MB/s
Collecting smmap<6,>=3.0.1
  Downloading smmap-5.0.0-py3-none-any.whl (24 kB)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata>=1.4->streamlit) (3.8.0)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /usr/local/lib/python3.7/dist-packages (from jsonschema>=3.0->altair>=3.2.0->streamlit) (0.18.1)
Requirement already satisfied: importlib-resources>=1.4.0 in /usr/local/lib/python3.7/dist-packages (from jsonschema>=3.0->altair>=3.2.0->streamlit) (5.7.1)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.21.0->streamlit) (2022.1)
Requirement already satisfied: six>=1.9 in /usr/local/lib/python3.7/dist-packages (from protobuf<4,>=3.12->streamlit) (1.15.0)
Collecting ipykernel>=5.1.2
  Downloading ipykernel-6.15.0-py3-none-any.whl (133 kB)
     |████████████████████████████████| 133 kB 47.9 MB/s
Requirement already satisfied: traitlets>=4.3.2 in /usr/local/lib/python3.7/dist-packages (from pydeck>=0.1.dev5->streamlit) (5.1.1)
Requirement already satisfied: ipywidgets>=7.0.0 in /usr/local/lib/python3.7/dist-packages (from pydeck>=0.1.dev5->streamlit) (7.7.0)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.7/dist-packages (from ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit) (1.5.5)
Collecting ipython>=7.23.1
  Downloading ipython-7.34.0-py3-none-any.whl (793 kB)
     |████████████████████████████████| 793 kB 47.9 MB/s
Collecting tornado>=5.0
  Downloading tornado-6.1-cp37-cp37m-manylinux2010_x86_64.whl (428 kB)
     |████████████████████████████████| 428 kB 47.4 MB/s
Requirement already satisfied: psutil in /usr/local/lib/python3.7/dist-packages (from ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit) (5.4.8)
Requirement already satisfied: pyzmq>=17 in /usr/local/lib/python3.7/dist-packages (from ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit) (23.1.0)
Requirement already satisfied: debugpy>=1.0 in /usr/local/lib/python3.7/dist-packages (from ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit) (1.0.0)
Requirement already satisfied: matplotlib-inline>=0.1 in /usr/local/lib/python3.7/dist-packages (from ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit) (0.1.3)
Collecting jupyter-client>=6.1.12
  Downloading jupyter_client-7.3.4-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB 47.6 MB/s
Requirement already satisfied: decorator in /usr/local/lib/python3.7/dist-packages (from ipython>=7.23.1->ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.7/dist-packages (from ipython>=7.23.1->ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit) (0.7.5)
Collecting prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0
  Downloading prompt_toolkit-3.0.30-py3-none-any.whl (381 kB)
     |████████████████████████████████| 381 kB 41.2 MB/s
Requirement already satisfied: jedi>=0.16 in /usr/local/lib/python3.7/dist-packages (from ipython>=7.23.1->ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit) (0.18.1)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.7/dist-packages (from ipython>=7.23.1->ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit) (4.8.0)
Requirement already satisfied: pygments in /usr/local/lib/python3.7/dist-packages (from ipython>=7.23.1->ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit) (2.6.1)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.7/dist-packages (from ipython>=7.23.1->ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit) (57.4.0)
Requirement already satisfied: backcall in /usr/local/lib/python3.7/dist-packages (from ipython>=7.23.1->ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit) (0.2.0)
Requirement already satisfied: nbformat>=4.2.0 in /usr/local/lib/python3.7/dist-packages (from ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit) (5.4.0)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit) (1.1.0)
Requirement already satisfied: widgetsnbextension~=3.6.0 in /usr/local/lib/python3.7/dist-packages (from ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit) (3.6.0)
Requirement already satisfied: ipython-genutils~=0.2.0 in /usr/local/lib/python3.7/dist-packages (from ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit) (0.2.0)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /usr/local/lib/python3.7/dist-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit) (0.8.3)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/dist-packages (from jinja2->altair>=3.2.0->streamlit) (2.0.1)
Requirement already satisfied: jupyter-core>=4.9.2 in /usr/local/lib/python3.7/dist-packages (from jupyter-client>=6.1.12->ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit) (4.10.0)
Requirement already satisfied: fastjsonschema in /usr/local/lib/python3.7/dist-packages (from nbformat>=4.2.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit) (2.15.3)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.7/dist-packages (from pexpect>4.3->ipython>=7.23.1->ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.7/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=7.23.1->ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit) (0.2.5)
Requirement already satisfied: notebook>=4.4.1 in /usr/local/lib/python3.7/dist-packages (from widgetsnbextension~=3.6.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit) (5.3.1)
Requirement already satisfied: nbconvert in /usr/local/lib/python3.7/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit) (5.6.1)
Requirement already satisfied: terminado>=0.8.1 in /usr/local/lib/python3.7/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit) (0.13.3)
Requirement already satisfied: Send2Trash in /usr/local/lib/python3.7/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit) (1.8.0)
Requirement already satisfied: bleach in /usr/local/lib/python3.7/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit) (5.0.0)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.7/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit) (1.5.0)
Requirement already satisfied: mistune<2,>=0.8.1 in /usr/local/lib/python3.7/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit) (0.8.4)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.7/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit) (0.7.1)
Requirement already satisfied: testpath in /usr/local/lib/python3.7/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit) (0.6.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.7/dist-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit) (0.5.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging->streamlit) (3.0.9)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->streamlit) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->streamlit) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->streamlit) (2022.6.15)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->streamlit) (2.10)
Collecting commonmark<0.10.0,>=0.9.0
  Downloading commonmark-0.9.1-py2.py3-none-any.whl (51 kB)
     |████████████████████████████████| 51 kB 6.6 MB/s
Building wheels for collected packages: blinker, validators
  Building wheel for blinker (setup.py) ... done
  Created wheel for blinker: filename=blinker-1.4-py3-none-any.whl size=13478 sha256=79f63d1875e1b756f5975a1ab5d70f4b4e94afe05b84d278ccba5c8899074b6e
  Stored in directory: /root/.cache/pip/wheels/22/f5/18/df711b66eb25b21325c132757d4314db9ac5e8dabeaf196eab
  Building wheel for validators (setup.py) ... done
  Created wheel for validators: filename=validators-0.20.0-py3-none-any.whl size=19582 sha256=d3e750823fdc669bf43613775e7be9d3cd6fac9c7aa911373d7f82e745f39121
  Stored in directory: /root/.cache/pip/wheels/5f/55/ab/36a76989f7f88d9ca7b1f68da6d94252bb6a8d6ad4f18e04e9
Successfully built blinker validators
Installing collected packages: tornado, prompt-toolkit, jupyter-client, ipython, ipykernel, smmap, gitdb, commonmark, watchdog, validators, toml, rich, pympler, pydeck, gitpython, blinker, streamlit
  Attempting uninstall: tornado
    Found existing installation: tornado 5.1.1
    Uninstalling tornado-5.1.1:
      Successfully uninstalled tornado-5.1.1
  Attempting uninstall: prompt-toolkit
    Found existing installation: prompt-toolkit 1.0.18
    Uninstalling prompt-toolkit-1.0.18:
      Successfully uninstalled prompt-toolkit-1.0.18
  Attempting uninstall: jupyter-client
    Found existing installation: jupyter-client 5.3.5
    Uninstalling jupyter-client-5.3.5:
      Successfully uninstalled jupyter-client-5.3.5
  Attempting uninstall: ipython
    Found existing installation: ipython 5.5.0
    Uninstalling ipython-5.5.0:
      Successfully uninstalled ipython-5.5.0
  Attempting uninstall: ipykernel
    Found existing installation: ipykernel 4.10.1
    Uninstalling ipykernel-4.10.1:
      Successfully uninstalled ipykernel-4.10.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
nbclient 0.6.4 requires traitlets>=5.2.2, but you have traitlets 5.1.1 which is incompatible.
jupyter-console 5.2.0 requires prompt-toolkit<2.0.0,>=1.0.0, but you have prompt-toolkit 3.0.30 which is incompatible.
google-colab 1.0.0 requires ipykernel~=4.10, but you have ipykernel 6.15.0 which is incompatible.
google-colab 1.0.0 requires ipython~=5.5.0, but you have ipython 7.34.0 which is incompatible.
google-colab 1.0.0 requires tornado~=5.1.0; python_version >= "3.0", but you have tornado 6.1 which is incompatible.
Successfully installed blinker-1.4 commonmark-0.9.1 gitdb-4.0.9 gitpython-3.1.27 ipykernel-6.15.0 ipython-7.34.0 jupyter-client-7.3.4 prompt-toolkit-3.0.30 pydeck-0.7.1 pympler-1.0.1 rich-12.4.4 smmap-5.0.0 streamlit-1.10.0 toml-0.10.2 tornado-6.1 validators-0.20.0 watchdog-2.1.9

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pyngrok===4.1.1
  Downloading pyngrok-4.1.1.tar.gz (18 kB)
Requirement already satisfied: future in /usr/local/lib/python3.7/dist-packages (from pyngrok===4.1.1) (0.16.0)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.7/dist-packages (from pyngrok===4.1.1) (3.13)
Building wheels for collected packages: pyngrok
  Building wheel for pyngrok (setup.py) ... done
  Created wheel for pyngrok: filename=pyngrok-4.1.1-py3-none-any.whl size=15983 sha256=75febdd68c3e9c028f5fc78f67e8020e1c10af2d4df91de5d74cda6e86c3c7b3
  Stored in directory: /root/.cache/pip/wheels/b1/d9/12/045a042fee3127dc40ba6f5df2798aa2df38c414bf533ca765
Successfully built pyngrok
Installing collected packages: pyngrok
Successfully installed pyngrok-4.1.1

In [61]:
%%writefile diagnosis-rct-app.py
import streamlit as st
import base64
import sklearn
import numpy as np
import pickle as pkl
from sklearn.preprocessing import MinMaxScaler
scal=MinMaxScaler()
#Load the saved model
model=pkl.load(open("final_model.p","rb"))





st.set_page_config(page_title="rct App",page_icon="⚕️",layout="centered",initial_sidebar_state="expanded")



def preprocess(sex,age,side,trauma,jobe,bear,belly,erls,ss,IS,ssc,ases,const,ucla,flex,abd,er,ir,vas,time ):   
 
    
    # Pre-processing user input   
    if sex=="male":
        sex=0
    else: sex=1
    
    #age
        
    if side=="Yes":
        side=1 
    else: side=0
        
    if vas=="0-4":
        vas=0
    elif vas == "5-7"：
        vas=1
    else：vas=2
    
    if time=="0-3":
        time=0
    elif time == "3-6"：
        time=1
    elif time == "6-12"：
        time=2
    else：time = 3
        
    if trauma=="Yes":
        trauma=1 
    else: trauma=0
        
    if flex=="0-45":
        flex=0
    elif flex == "45-90"：
        flex=1
    elif flex == "90-135"：
        flex=2
    else：flex = 3
        
    if abd=="0-45":
        abd=0
    elif abd == "45-90"：
        abd=1
    elif abd == "90-135"：
        abd=2
    else：abd = 3
        
    if er=="0-20":
        er=0
    elif er == "20-40"：
        er=1
    elif er == "40-60"：
        er=2
    else：er = 3
        
    if ir=="below S1":
        ir=0
    elif ir == "L1-L5"：
        ir=1
    else：ir = 2
    
    if jobe=="+":
        jobe=1 
    else: jobe=0
        
    if bear=="+":
        bear=1 
    else: bear= 0
        
    if belly=="+":
        belly=1 
    else: belly= 0
    
    if erls=="+":
        erls=1 
    else: erls= 0
        
    # ss is ssc ases const ucla
    
    
    

    user_input=[sex,age,side,trauma,jobe,bear,belly,erls,ss,IS,ssc,ases,const,ucla,flex,abd,er,ir,vas,time ]
    user_input=np.array(user_input)
    user_input=user_input.reshape(1,-1)
    user_input=scal.fit_transform(user_input)
    prediction = model.predict(user_input)

    return prediction

    

       
    # front end elements of the web page 
html_temp = """ 
    <div style ="background-color:pink;padding:13px"> 
    <h1 style ="color:black;text-align:center;">Healthy Heart App</h1> 
    </div> 
    """
      
# display the front end aspect
st.markdown(html_temp, unsafe_allow_html = True) 
st.subheader('by Amlan Mohanty ')
      
# following lines create boxes in which user can enter data required to make prediction
age=st.selectbox ("Age",range(1,121,1))
sex = st.radio("Select Gender: ", ('male', 'female'))
side=st.radio("is the painful shoulder your dominant side?", ['Yes','No'])
trauma=st.radio("have you get injuried in your shoulder?", ['Yes','No'])
jobe=st.radio("JOBE test", ['+','-'])
bear=st.radio("BEAR HUG", ['+','-'])
belly=st.radio("BELLY PRESS", ['+','-'])
erls=st.radio("ERLS", ['+','-'])
ss=st.selectbox('the strength of supraspinatus ',range(0,5,1))
IS=st.selectbox('the strength of infraspinatus',range(0,5,1)) 
ssc=st.selectbox('the strength of subscapularis ',range(0,5,1))
ases=st.selectbox ("ASES",range(1,100,1))
const=st.selectbox ("Constant-Murley",range(1,100,1))
ucla=st.selectbox ("UCLA",range(1,100,1))
vas,time 
flex=st.selectbox('Flexion',("0-45°","45-90°","90-135°","135-180°"))
abd=st.selectbox('Abduction',("0-45°","45-90°","90-135°","135-180°"))
er=st.selectbox('External rotation',("0-20°","20-40°","40-60°","60-80°"))
ir=st.selectbox('Internal rotation',("below S1","L1-L5","above T12"))
vas=st.selectbox('VAS',("0-4","5-7","8-10°"))
time=st.selectbox('Duration of symptoms/months',("<3","3-6","6-12",">12"))




# cp = st.selectbox('Chest Pain Type',("Typical angina","Atypical angina","Non-anginal pain","Asymptomatic")) 
# trestbps=st.selectbox('Resting Blood Sugar',range(1,500,1))
# restecg=st.selectbox('Resting Electrocardiographic Results',("Nothing to note","ST-T Wave abnormality","Possible or definite left ventricular hypertrophy"))
# chol=st.selectbox('Serum Cholestoral in mg/dl',range(1,1000,1))
# fbs=st.radio("Fasting Blood Sugar higher than 120 mg/dl", ['Yes','No'])
# thalach=st.selectbox('Maximum Heart Rate Achieved',range(1,300,1))
# exang=st.selectbox('Exercise Induced Angina',["Yes","No"])
# oldpeak=st.number_input('Oldpeak')




#user_input=preprocess(sex,cp,exang, fbs, slope, thal )
pred=preprocess(age,sex,cp,trestbps,restecg,chol,fbs,thalach,exang,oldpeak,slope,ca,thal)




if st.button("Predict"):    
 if pred[0] == 0:
    st.error('Warning! You have high risk of getting a rct!')
    
 else:
    st.success('You have lower risk of getting a rct!')
    
   

st.sidebar.subheader("About App")

st.sidebar.info("This web app is helps you to find out whether you are at a risk of developing a RCT.")
st.sidebar.info("Enter the required fields and click on the 'Predict' button to check whether you have a healthy shoulder")
st.sidebar.info("Don't forget to rate this app")



feedback = st.sidebar.slider('How much would you rate this app?',min_value=0,max_value=5,step=1)

if feedback:
  st.header("Thank you for rating the app!")
  st.info("Caution: This is just a prediction and not doctoral advice. Kindly see a doctor if you feel the symptoms persist.")

Writing diagnosis-rct-app.py

In [62]:
!nohup streamlit run healthy-heart-app.py &
url = ngrok.connect(port='8501')
url

nohup: appending output to 'nohup.out'

'http://392b-34-136-100-112.ngrok.io'